### ISSUE TITLE
15/12 update

### ISSUE THREAD

**Issue by XelZero** [michengs/Dungeon-guide#6]
getting error in VS (conquest):

[23:16:41.890] [dungeon-guide] ERROR: Error: [dispatch] write: failed to generate S_SPAWN_DROPITEM<8>:
Error: version 8 of message (name: "S_SPAWN_DROPITEM", code: 41375) is outdated and cannot be used anymore
    at Dispatch.write (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\node_modules\tera-network-proxy\lib\connection\dispatch.js:316:23)
    at NetworkModInterface.send (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\bin\mod.js:343:38)
    at Object.module.exports.spawn (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\events\handlers\spawn.js:112:19)
    at Handlers.<anonymous> (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:64:44)
    at Handlers.emit (events.js:223:5)
    at C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:112:17
    at Handlers.delay (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:131:4)
    at Handlers.trigger (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:106:15)
    at Object.__types.<computed> [as spawn] (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\core\handlers.js:73:19)
    at Item.render (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox-Brawl\mods\guide-core\lib\spawn.js:317:18)****

**Comment by michengs** [comment]
> VS中出现错误（征服）：
> 
> [23：16：41.890] [地牢指南]错误：错误：[调度]写入：无法生成S_SPAWN_DROPITEM <8>：
> 错误：消息的版本8（名称：“ S_SPAWN_DROPITEM”，代码：41375）已过时且无法可以 在NetworkModInterface.send的
> Dispatch.write（C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ node_modules \ tera-network-proxy \ lib \ connection \ dispatch.js：316：23）
> 中使用C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ bin \ mod.js：343：38）
> 位于Object.module.exports.spawn（C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox -处理程序中的-Brawl \ mods \ guide-core \ lib \ core \ events \ handlers \ spawn.js：112：19）
> 。（C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ mods \ guide-core \ lib \ core \ handlers.js：64：44）
> 在Handlers.emit（events.js：223：5）
> 在C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ mods \ guide-core \ lib \ core \ handlers.js：112：17
> 在Handlers.delay（C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ mods \ guide-core \ lib \ core \ handlers.js：131：4）
> 在Handlers.trigger（C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ mods \ guide -core \ lib \ core \ handlers.js：106：15），
> 位于Object .__ types。[作为生成]（C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ mods \ guide-core \ lib \ core \ handlers.js：73：19）
> 在Item.render（C：\ Users \ XXXXX \ AppData \ Local \ Programs \ TeraToolbox-Brawl \ mods \ guide-core \ lib \ spawn.js：317：18）****

**Comment by michengs** [comment]
It is all right now.

**Comment by XelZero** [comment]
i am off to bed - but i did just reload it right before to see if update or anything - but will reload again tomorrow to see if it persist
