### ISSUE TITLE
MM - 9070

### ISSUE THREAD

**Issue by XelZero** [michengs/Dungeon-guide#7]
this guide use to support Manglemire but no longer seems to (either this or the core mode) - its still built into the GUI but there isn't any update to the guide - its not a big deal as its an easy easy dgn but i am getting error if you'd like to maybe get it updated

[dungeon-guide] ERROR: Unable to load a script for the guide "9070":
 C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\Dungeon-guide-master\guides\9070.js:178
  {"type": "func","func": skilld_event.bind(null, 000)}
                                                  ^^^

SyntaxError: Octal literals are not allowed in strict mode.
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at wrapSafe (internal/modules/cjs/loader.js:1047:15)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)

**Comment by justkeepquiet** [comment]
Try to use this one https://github.com/hsdn/tera-guide/blob/master/guides/9070.js

**Comment by Loliconera** [comment]
Michengs already added updated MM guid

**Comment by XelZero** [comment]
18 days ago wasn't there... Update was yesterday... Never needed but hate errors...
